# -*- coding: utf-8 -*-
"""logistic regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o4kwdnnCB7yUcUvs1Qa6IqRP9bK8jPDx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("diabetes_eda_dataset (1).csv")

df

df.info()

df['Outcome']

df.isnull().sum()

sns.boxplot(df['Glucose'])

sns.boxplot(df['BloodPressure'])

sns.boxplot(df['Insulin'])

sns.boxplot(df['BMI'])

df['Glucose']=df['Glucose'].fillna(df['Glucose'].mean())
df['BloodPressure']=df['BloodPressure'].fillna(df['BloodPressure'].mean())
df['Insulin']=df['Insulin'].fillna(df['Insulin'].mean())
df['BMI']=df['BMI'].fillna(df['BMI'].mean())

df.info()

#feature engineering on BMI

df['BMI_Category']=pd.cut(df['BMI'],
     bins=[0,18.5,25,30,100],
     labels=['Underweight','Normal','Overweight','Obese'])

df=pd.get_dummies(df, columns=['BMI_Category'], drop_first=True)

df

df.info()

df['Age_Category']=pd.cut(df['Age'],
     bins=[0,12,20,30,59],
     labels=['Child','Teenager','Adult','Senior'])

df=pd.get_dummies(df, columns=['Age_Category'], drop_first=True)

df

df['Glucose']

df['High_Glucose']=np.where(df['Glucose'] >=140,1,0)

df['Insulin']

df['High_Insulin']=np.where(df['Insulin'] >=25,1,0)

df.info()

df.shape

df.drop('SkinThickness', axis=1, inplace=True)

df.shape

x= df.drop('Outcome',axis=1)

x.shape

y=df['Outcome']

y.shape

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

X_scaled=scaler.fit_transform(x)

X=pd.DataFrame(X_scaled, columns=x.columns)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test=train_test_split(X_scaled,y, test_size=0.2,random_state=42)

#choose the model

from sklearn.linear_model import LogisticRegression

model=LogisticRegression()

model.fit(x_train,y_train)

y_pred=model.predict(x_test)

y_pred_prob=model.predict_proba(x_test)

from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test,y_pred)

cm

from sklearn.metrics import accuracy_score

acc=accuracy_score(y_test,y_pred)

acc

df.info()

from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))

import pandas as pd
import numpy as np

def predict_diabetes(Pregnancies, Glucose, BloodPressure, Insulin, BMI, Age):
  new_df=pd.DataFrame([{
      'Pregnancies':Pregnancies,
      'Glucose':Glucose,
      'BloodPressure':BloodPressure,
      'Insulin':Insulin,
      'BMI':BMI,
      'Age':Age
  }])

  #Feature engineering
  new_df['High_Glucose']=np.where(new_df['Glucose'] >=140,1,0)
  new_df['High_Insulin']=np.where(new_df['Insulin'] >=25,1,0)

 #Align with training columns
  for col in x.columns:
   if col not in new_df.columns:
     new_df[col]=0
  new_df=new_df[x.columns]

  #Scale and predict
  new_scaled=scaler.transform(new_df)
  pred=model.predict(new_scaled)[0]

  return "Yes" if pred==1 else "No"

result= predict_diabetes (2,160,75,130,0.6,45)
print(result)

